# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/canonical-rails/all/canonical-rails.rbi
#
# canonical-rails-0.2.11

module CanonicalRails
  def allowed_parameters; end
  def allowed_parameters=(obj); end
  def collection_actions; end
  def collection_actions=(obj); end
  def host; end
  def host=(obj); end
  def opengraph_url; end
  def opengraph_url=(obj); end
  def port; end
  def port=(obj); end
  def protocol; end
  def protocol=(obj); end
  def self.allowed_parameters; end
  def self.allowed_parameters=(obj); end
  def self.collection_actions; end
  def self.collection_actions=(obj); end
  def self.host; end
  def self.host=(obj); end
  def self.opengraph_url; end
  def self.opengraph_url=(obj); end
  def self.port; end
  def self.port=(obj); end
  def self.protocol; end
  def self.protocol=(obj); end
  def self.setup; end
  def self.sym_allowed_parameters; end
  def self.sym_collection_actions; end
  def self.whitelisted_parameters; end
  def self.whitelisted_parameters=(obj); end
  def whitelisted_parameters; end
  def whitelisted_parameters=(obj); end
end
module CanonicalRails::TagHelper
  def allowed_params; end
  def allowed_query_string; end
  def canonical_host; end
  def canonical_href(host = nil, port = nil, force_trailing_slash = nil); end
  def canonical_path(force_trailing_slash = nil); end
  def canonical_port; end
  def canonical_protocol; end
  def canonical_tag(host = nil, port = nil, force_trailing_slash = nil); end
  def convert_numeric_params(params_hash); end
  def path_without_html_extension; end
  def trailing_slash_config(force_trailing_slash = nil); end
  def trailing_slash_if_needed; end
  def trailing_slash_needed?; end
end
class CanonicalRails::Engine < Rails::Engine
end
