# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/discard/all/discard.rbi
#
# discard-1.2.0

module Discard
end
class Discard::DiscardError < StandardError
end
class Discard::RecordNotDiscarded < Discard::DiscardError
  def initialize(message = nil, record = nil); end
  def record; end
end
class Discard::RecordNotUndiscarded < Discard::DiscardError
  def initialize(message = nil, record = nil); end
  def record; end
end
module Discard::Model
  def _raise_record_not_discarded; end
  def _raise_record_not_undiscarded; end
  def discard!; end
  def discard; end
  def discarded?; end
  def kept?; end
  def undiscard!; end
  def undiscard; end
  def undiscarded?; end
  extend ActiveSupport::Concern
end
module Discard::Model::ClassMethods
  def discard_all!; end
  def discard_all; end
  def undiscard_all!; end
  def undiscard_all; end
end
