# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/fast_sqlite/all/fast_sqlite.rbi
#
# fast_sqlite-0.0.1

module FastSqlite
end
class SQLite3::Database
  def gotta_go_fast!; end
  def initialize_original(file, options = nil, zvfs = nil); end
end
