# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails-i18n/all/rails-i18n.rbi
#
# rails-i18n-6.0.0

module RailsI18n
end
class RailsI18n::Railtie < Rails::Railtie
  def self.add(pattern); end
  def self.init_pluralization_module; end
  def self.pattern_from(args); end
end
module RailsI18n::Pluralization
end
module RailsI18n::Pluralization::Other
  def self.rule; end
  def self.with_locale(locale); end
end
module RailsI18n::Pluralization::OneWithZeroOther
  def self.rule; end
  def self.with_locale(locale); end
end
module RailsI18n::Pluralization::OneTwoOther
  def self.rule; end
  def self.with_locale(locale); end
end
module RailsI18n::Pluralization::OneOther
  def self.rule; end
  def self.with_locale(locale); end
end
module RailsI18n::Pluralization::EastSlavic
  def self.rule; end
  def self.with_locale(locale); end
end
module RailsI18n::Pluralization::OneUptoTwoOther
  def self.rule; end
  def self.with_locale(locale); end
end
module RailsI18n::Pluralization::Romanian
  def self.rule; end
  def self.with_locale(locale); end
end
module RailsI18n::Pluralization::WestSlavic
  def self.rule; end
  def self.with_locale(locale); end
end
