# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/truncate_html/all/truncate_html.rbi
#
# truncate_html-0.9.3

module TruncateHtml
  def self.configuration; end
  def self.configuration=(arg0); end
  def self.configure; end
end
class TruncateHtml::HtmlTruncator
  def append_to_result(token); end
  def build_output; end
  def close_open_tags; end
  def initialize(original_html, options = nil); end
  def process_token(token); end
  def remove_latest_open_tag(close_tag); end
  def truncate; end
  def truncate_token?(token); end
  def word_boundary; end
end
class TruncateHtml::HtmlString < String
  def html_comment?; end
  def html_tag?; end
  def html_tokens; end
  def initialize(original_html); end
  def matching_close_tag; end
  def open_tag?; end
end
class TruncateHtml::Configuration
  def break_token; end
  def break_token=(arg0); end
  def length; end
  def length=(arg0); end
  def omission; end
  def omission=(arg0); end
  def word_boundary; end
  def word_boundary=(arg0); end
end
module TruncateHtmlHelper
  def truncate_html(html, options = nil); end
end
