# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/with_model/all/with_model.rbi
#
# with_model-2.1.4

module WithModel
  def with_model(name, scope: nil, **options, &block); end
  def with_table(name, scope: nil, **options, &block); end
end
class WithModel::ConstantStubber
  def basename; end
  def initialize(const_name); end
  def lookup_list; end
  def namespace; end
  def stub_const(value); end
  def unstub_const; end
end
module WithModel::Methods
  def with_model?; end
end
class WithModel::Table
  def connection; end
  def create; end
  def destroy; end
  def exists?; end
  def initialize(name, options = nil, &block); end
end
class WithModel::Model
  def cleanup_descendants_tracking; end
  def const_name; end
  def create; end
  def destroy; end
  def initialize(name, superclass: nil); end
  def model_block=(arg0); end
  def reset_dependencies_cache; end
  def setup_model; end
  def stubber; end
  def table; end
  def table_block=(arg0); end
  def table_name; end
  def table_options=(arg0); end
end
class WithModel::Model::DSL
  def initialize(model); end
  def model(&block); end
  def table(options = nil, &block); end
end
